name: Задача уровня проекта
description: Шаблон для больших проектных задач (эпиков)
title: "[EPIC] "
labels: ["epic"]

body:
  - type: markdown
    attributes:
      value: |
        Заполни форму ниже. Поля с * обязательны.

  - type: textarea
    id: context
    attributes:
      label: Контекст
      description: Вводные про задачу для общего понимания
      placeholder: Зачем нужна задача? Какую проблему решаем? Для кого?
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Зависимости
      description: Ссылки на зависимые задачи (уровня проекта) и комментарии — какие зависимости есть и что с ними делать
      placeholder: |
        Примеры:
        - Зависит от: #123, #456
        - Блокирует: #789
        Комментарии: ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Подзадачи
      description: Ссылки на саб-issues, которые определяют содержание этой большой задачи
      placeholder: |
        - [ ] #101 — Подзадача 1
        - [ ] #102 — Подзадача 2
      value: |
        - [ ] # — Подзадача
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Краткое описание ожидаемого результата
      description: Как поймём, что эпик завершён? Критерии приёмки.
      placeholder: |
        - Пользователь может …
        - Отчёт доступен по …
        - Метрика X ≥ Y
      render: markdown
    validations:
      required: true

  - type: input
    id: due
    attributes:
      label: Целевая дата (если есть)
      placeholder: "YYYY-MM-DD"

  # >>> МНОГОВЫБОР ИСПОЛНИТЕЛЕЙ <<<
  # В options впиши логины вашей команды (строго GitHub-юзернеймы)
  - type: dropdown
    id: assignees
    attributes:
      label: Исполнители
      description: Кого назначить на задачу (можно выбрать нескольких)
      multiple: true
      options:
        - user1
        - user2
        - user3
        - "@MaxTro91627"
    validations:
      required: false
